Dateformat
0x3D/MSDOS pull request #28
Opened 2021-05-19 11:22 UTC by jonasn-chalmers

Formaterat alla (tror jag) datum i applikationen så man kan läsa dom bra nu. Va ju vissa formateringar som fattades på vissa ställen, typ adminpage och under mina bokningar, ska vara löst nu. 

Om ni hittar fler ställen där det inte är formaterat, säg till så fixar jag.

2021-05-19 11:28 UTC, jonasn-chalmers commented
Ser att travis failar, klagar på:

import { sv } from 'date-fns/esm/locale'

tyvärr ingen aning om hur man löser

2021-05-19 12:35 UTC, 0x3D requested changes
I would like that you implement my changes. Human readable format is very Ambigious and what PPPP means is also not crystal clear. Several different programming langugages have different letters for how to format. 
I added an example that would suffice to make me happy.

2021-05-19 12:35 UTC, 0x3D commented on src/DateFormatter.js
> + * Function to format a date to a human readable time
```suggestion
 * Function to format a date to the format H:mm which looks like 17:32
```

2021-05-19 12:35 UTC, 0x3D commented on src/DateFormatter.js
> + * Function to format a date to a human readable day
```suggestion
 * Function to format a date to the format  PPPP which looks like Friday, April 29th, 1453
```

2021-05-19 12:35 UTC, 0x3D commented
Also Travis fail and I do not understand why

2021-05-19 12:41 UTC, axelhertzberg approved these changes
Dunder bra! Det kanske du redan har gjort men kolla så allt funkar med java server

2021-05-19 13:32 UTC, jonasn-chalmers commented
> Dunder bra! Det kanske du redan har gjort men kolla så allt funkar med java server

Ska inte vara några problem eftersom den varken postar eller gettar något.

2021-05-19 13:46 UTC, jonasn-chalmers commented
Fixat travis nu och docs är uppdaterade!

2021-05-20 07:43 UTC, erikbengtssonchalmers approved these changes
Gott tryckt!

2021-05-20 08:16 UTC, 0x3D approved these changes

2021-05-20 08:17 UTC, merged